version: "3.9"
services:
  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/model
      - AI_API_KEY=${AI_API_KEY}
      - AI_API_SECRET=${AI_API_SECRET}
    volumes:
      - ./ai-service:/app

  image-processor:
    build: ./image-processor
    ports:
      - "8001:8001"
    environment:
      - IMAGE_API_KEY=${IMAGE_API_KEY}
      - IMAGE_API_SECRET=${IMAGE_API_SECRET}

  init-mongo-replica:
    image: mongo
    depends_on:
      - mongo-write
      - mongo-read
    volumes:
      - ./init-replica.sh:/init-replica.sh:ro
    entrypoint: ["sh", "/init-replica.sh"]

  db-healthcheck:
    build: ./db-healthcheck
    environment:
      # SỬA ĐỂ SỬ DỤNG lung_app THAY VÌ mydb
      - MONGO_URI_WRITE=mongodb://mongo-write:27017/lung_app?replicaSet=rs0
      - MONGO_URI_READ=mongodb://mongo-read:27017/lung_app?replicaSet=rs0
    depends_on:
      - mongo-write
      - mongo-read
    ports:
      - "9990:9990"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev"

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI_WRITE=mongodb://mongo-write:27017/lung_app
      - MONGO_URI_READ=mongodb://mongo-read:27017/lung_app
      - DATABASE_NAME=lung_app  # THÊM BIẾN MÔI TRƯỜNG NÀY
      - PORT=4000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AI_API_KEY=${AI_API_KEY}
      - AI_API_SECRET=${AI_API_SECRET}
      - IMAGE_API_KEY=${IMAGE_API_KEY}
      - IMAGE_API_SECRET=${IMAGE_API_SECRET}
    depends_on:
      - mongo-write
      - mongo-read
      - redis

  mongo-write:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_write_data:/data/db
    command: --replSet rs0

  mongo-read:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_read_data:/data/db
    command: --replSet rs0

  mongo-express-write:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-write
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin

  mongo-express-read:
    image: mongo-express
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-read
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_write_data:
  mongo_read_data:
  redis_data: